name: CTF
version: '${project.version}'
main: me.slicecraft.ctf.CTF
api-version: 1.18
author: SliceCraft
depend: [WorldEdit]
commands:
  disable:
    description: Disable the plugin
    usage: /<command>